info:
  description: Contains players, games and teams data from the National Basket Ball
    Association (NBA). Data is available from seasons 1979 to current date.
  title: balldontlie
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/v1/games:
    get:
      operationId: getGames
      parameters:
      - description: An array of seasons
        example: '2018'
        in: query
        name: seasons[]
        schema:
          items:
            type: integer
          type: array
      - example: '1'
        in: query
        name: team_ids[]
        schema:
          items:
            type: integer
          type: array
      - description: An array of dates formatted in 'YYYY-MM-DD'
        in: query
        name: dates[]
        schema:
          items:
            type: string
          type: array
      - description: A single date in 'YYYY-MM-DD' format. This is used to select
          games that occur on or after this date.
        in: query
        name: start_date
        schema:
          items:
            type: string
          type: array
      - description: A single date in 'YYYY-MM-DD' format. This is used to select
          games that occur on or before this date.
        in: query
        name: end_date
        schema:
          type: string
      - description: The page number, used for pagination.
        in: query
        name: page
        schema:
          default: 0
          type: integer
      - description: The number of results returned per call, used for pagination.
          Max 100.
        in: query
        name: per_page
        schema:
          default: 25
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information about NBA games
      tags:
      - games
  /api/v1/games/{gameId}:
    get:
      operationId: getGamesById
      parameters:
      - description: The ID of the game to retrieve
        example: 123
        in: path
        name: gameId
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information on a specific game
      tags:
      - games
  /api/v1/players:
    get:
      operationId: getPlayers
      parameters:
      - description: Used to filter players based on their name. For example, ?search=davis
          will return players that have 'davis' in their first or last name.
        example: lebron
        in: query
        name: search
        schema:
          type: string
      - description: The page number, used for pagination.
        in: query
        name: page
        schema:
          default: 0
          type: integer
      - description: The number of results returned per call, used for pagination.
          Max 100.
        in: query
        name: per_page
        schema:
          default: 25
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information about players using search
      tags:
      - players
  /api/v1/players/{playerId}:
    get:
      operationId: getPlayersById
      parameters:
      - description: The ID of the player to retrieve
        example: 123
        in: path
        name: playerId
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information for a specific player
      tags:
      - players
  /api/v1/season_averages:
    get:
      operationId: getSeasonAverages
      parameters:
      - description: A single season
        in: query
        name: season
        schema:
          default: current_season
          type: integer
      - description: An array of player_ids
        in: query
        name: player_ids[]
        schema:
          default: current_season
          items:
            type: integer
          type: array
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get season averages
      tags:
      - stats
      - players
  /api/v1/stats:
    get:
      operationId: getStats
      parameters:
      - example: '2018'
        in: query
        name: seasons[]
        schema:
          items:
            type: integer
          type: array
      - example: '1'
        in: query
        name: player_ids[]
        schema:
          items:
            type: integer
          type: array
      - in: query
        name: dates[]
        schema:
          items:
            type: string
          type: array
      - in: query
        name: start_date
        schema:
          type: string
      - in: query
        name: end_date
        schema:
          type: string
      - description: The page number, used for pagination.
        in: query
        name: page
        schema:
          default: 0
          type: integer
      - description: The number of results returned per call, used for pagination.
          Max 100.
        in: query
        name: per_page
        schema:
          default: 25
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get player statistics based on query parameters
      tags:
      - stats
  /api/v1/teams:
    get:
      operationId: getTeams
      parameters:
      - description: The page number, used for pagination.
        in: query
        name: page
        schema:
          default: 0
          type: integer
      - description: The number of results returned per call, used for pagination.
        in: query
        name: per_page
        schema:
          default: 10
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information about teams
      tags:
      - teams
  /api/v1/teams/{teamId}:
    get:
      operationId: getTeamsById
      parameters:
      - description: The ID of the team to retrieve
        in: path
        name: teamId
        required: true
        schema:
          default: 123
          type: integer
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response
      summary: Get information on a specific team
      tags:
      - teams
servers:
- url: https://www.balldontlie.io
tags:
- name: players
- name: teams
- name: games
- name: stats
